import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/Header/Header";
import Hero from "@/components/HeroSection/HeroSection";
import TestimonialSection from "@/components/TestimonialSection/TestimonialSection";
import OurProductsSection from "@/components/OurProductsSection/OurProductsSection";
import Brands from "@/components/Brands/Brands";
import CollectionsSection from "@/components/CollectionsSection/CollectionsSection";
import TeamSection from "@/components/TeamSection/TeamSection";
import Footer from "@/components/Footer/Footer";
import Showroom from "@/components/Showroom/Showroom";

export default function Home() {
  return (
    <>
      <Head>
        <title>Paintings Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Hero />
        <TestimonialSection />
        <OurProductsSection />
        <Brands />
        <Showroom />
        <CollectionsSection />
        <TeamSection />
        <Footer />
      </main>
    </>
  );
}
